### ISSUE TITLE
Cannot load files... 

### ISSUE THREAD

**Issue by mmahalwy** [justin808/bootstrap-sass-loader#22]
So it finds and logs the file, all is good. And now it cannot load it for some reason and pointing to the wrong please for the error. All in all, it cannot import the bootstrap-config file...

here is the log:
```
[boostrap-sass-loader]: styleLoader: /Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style-loader!css-loader!autoprefixer!sass?outputStyle=expanded
[boostrap-sass-loader]: bootstrap-sass location: /Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/bootstrap-sass/assets
[boostrap-sass-loader]: Setting: $icon-font-path: 'node_modules/bootstrap-sass/assets/fonts/bootstrap/';
[boostrap-sass-loader]: fileName for preBootstrapCustomizations: /Users/mmahalwy/Desktop/Code/quran.com/frontend/src/styles/_bootstrap-config.scss
[boostrap-sass-loader]: fileName for mainSass: /Users/mmahalwy/Desktop/Code/quran.com/frontend/src/styles/_main.scss
Hash: 0865bbc60349c612e85a
Version: webpack 1.10.3
Time: 15497ms
      Asset       Size  Chunks             Chunk Names
    main.js       2 MB       0  [emitted]  main
main.js.map    2.33 MB       0  [emitted]  main
 index.html  211 bytes          [emitted]
   [0] multi main 64 bytes {0} [built]
    + 491 hidden modules

ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./~/bootstrap-sass-loader/bootstrap-sass-styles.loader.js!./bootstrap-sass.config.js
Module build failed: ModuleBuildError: Module build failed:
var ExtractTextPlugin = require("extract-text-webpack-plugin");
       ^
      File to import not found or unreadable: Users/mmahalwy/Desktop/Code/quran.com/frontend/src/styles/bootstrap-config.scss
      in /Users/mmahalwy/Desktop/Code/quran.com/frontend/bootstrap-sass.config.js (line 1, column 9)
    at DependenciesBlock.onModuleBuildFailed (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.onRender (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/sass-loader/index.js:160:13)
    at options.error (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/node-sass/lib/index.js:279:32)
 @ ./~/bootstrap-sass-loader/index.loader.js!./bootstrap-sass.config.js 1:0-408
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./~/bootstrap-sass-loader/bootstrap-sass-styles.loader.js!./bootstrap-sass.config.js
    Module build failed:
    var ExtractTextPlugin = require("extract-text-webpack-plugin");
           ^
          File to import not found or unreadable: Users/mmahalwy/Desktop/Code/quran.com/frontend/src/styles/bootstrap-config.scss
          in /Users/mmahalwy/Desktop/Code/quran.com/frontend/bootstrap-sass.config.js (line 1, column 9)
```

I should mention that my files are named correctly: 
![image](https://cloud.githubusercontent.com/assets/3749095/8844319/a4784c20-30c8-11e5-8bda-e081598b8bda.png)

For some reason, it's looking for the non-partial file. When I remove that, then it errors saying it cannot find variables.scss from bootstrap. There must be something wrong with the import system? 

*update*
Notice: `unreadable: Users/mmahalwy/` it should be `unreadable: /Users/mmahalwy/`....

**Comment by justin808** [comment]
@mmahalwy Can you take look deeper into this? I haven't tried to use the extra text plugin in a long time. we had made a change sometime back to make this work on windows, and that may have caused the regression. I'm crazy busy right now, so I really appreciate the help. I wrote up some docs on how you can test this: https://github.com/justin808/bootstrap-sass-loader#testing-changes-in-the-bootstrap-sass-loader It shouldn't be too hard to find where the missing slash goes. Possibly some other dependency update broke this.

**Comment by mmahalwy** [comment]
@justin808 found the problem - its sass-loader 1.0.3 is not working or has a bug. Downgrading to 1.0.2 works fine... ugh spent ~2hrs on this...

**Comment by justin808** [comment]
@mmahalwy I think did the same one day!

**Comment by mmahalwy** [comment]
@justin808 thanks for your help! It is indeed a problem with sass-loader...
